### Estudando numerical python(NumPy)
 ##### o que o numpy permite:
 #####  Manipular objetos array multidimensionais, como matrizes e sequências
  ##### Realizar operações matemáticas e lógicas
  ##### Manipular formatos
  ##### Ordenar e selecionar
  ##### Utilizar ferramentas de estatística e cálculo
  ##### Gerar números aleatórios
  ##### Realizar álgebra linear
  ##### Executar transformadas discretas de Fourier

In [1]:
import numpy as np

In [2]:
# cria uma matriz unidimensional
mt = np.array([12,34,'a',26,18,10])
print(mt)
print(type(mt))

['12' '34' 'a' '26' '18' '10']
<class 'numpy.ndarray'>


In [7]:
#criar o array com um tipo específico
#cria o array como float de 64bits
mtfloat = np.array([1,2,3], dtype = np.float64)
print(mtfloat)
print(type(mtfloat))
mtint = np.array([1,2,3], dtype = np.int32)
print(mtint)
print(type(mtint))
#quando isso pode ser necessário?:
# Otimização de Memória:
#Para reduzir o uso de memória em grandes datasets. 
#Um array de int32 consome menos memória do que um de int64.


[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [20]:
#mudar o tipo do array
#É possível transformar tipos de dados de arrays
mtnew = np.array([1.4,3.6,5.1,9.42,4.99])
print(mtnew)
#quando transformados de float para int os valores são truncados
mtnewint = mtnew.astype(np.int32)
print(mtnewint)
#o inverso tambem pode ser feito.
mtnew2 = np.array([1,2,3,4])
print(mtnew2)
mtnew2int = mtnew2.astype(np.float32)
print(mtnew2int)

[1.4  3.6  5.1  9.42 4.99]
[1 3 5 9 4]
[1 2 3 4]
[1. 2. 3. 4.]


In [21]:
#matriz multidimensional
mt7 = np.array([[7,2,23],[12,27,4],[2,3,3]])
print(mt7)
            

[[ 7  2 23]
 [12 27  4]
 [ 2  3  3]]


In [22]:
matriz_2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matriz 2D:")
print(matriz_2D)

# Criar uma matriz 3x3x3 (3D)
matriz_3D = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                      [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
                      [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])
print("\nMatriz 3D:")
print(matriz_3D)

Matriz 2D:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matriz 3D:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [ ]:
# NumPy e Matrizes: Importância e Benefícios

# 1. Eficiência e Desempenho
# - NumPy é otimizado para operações com arrays e matrizes, permitindo cálculos mais rápidos
#   em comparação com listas nativas do Python.
# - Matrizes multidimensionais permitem manipular grandes volumes de dados de forma eficiente.

# 2. Representação de Dados Estruturados
# - Arrays 2D podem ser usados para representar tabelas (linhas e colunas).
# - Arrays 3D ou superiores são ideais para dados complexos, como imagens, séries temporais
#   e tensores usados em aprendizado de máquina.

# 3. Operações Matemáticas e Científicas
# - Suporte integrado para operações como multiplicação de matrizes, álgebra linear,
#   transformações e funções matemáticas avançadas.
# - Ideal para cálculos científicos e de engenharia.

# 4. Compatibilidade com Bibliotecas Avançadas
# - NumPy é a base de várias bibliotecas de ciência de dados e aprendizado de máquina,
#   como pandas, TensorFlow, PyTorch e scikit-learn.
# - Facilita a integração com ferramentas de análise de dados e computação científica.

# 5. Redução do Uso de Memória
# - Arrays NumPy usam menos memória do que listas ou estruturas nativas do Python,
#   especialmente ao trabalhar com grandes conjuntos de dados.

# 6. Manipulação de Dados de Alta Dimensionalidade
# - Matrizes multidimensionais tornam mais simples e intuitiva a manipulação de dados
#   complexos, como imagens (3D) ou dados temporais e espaciais (4D ou superiores).

# 7. Versatilidade
# - Permite facilmente realizar operações como somas, médias, transposições,
#   reshaping e slicing em dados estruturados.

# 8. Suporte para Operações Vetorizadas
# - Operações em arrays são vetorizadas, eliminando a necessidade de loops explícitos,
#   o que melhora o desempenho e reduz a complexidade do código.

# 9. Visualização e Análise
# - Arrays multidimensionais podem ser facilmente utilizados com bibliotecas de
#   visualização como Matplotlib para gerar gráficos e imagens.

# NumPy é uma ferramenta indispensável para processamento de dados, cálculos matemáticos
# e manipulação de estruturas de dados em Python, sendo amplamente utilizado
# em ciência de dados, inteligência artificial e computação científica.


In [4]:
#criar arrays vazios tipificados
#empty significa que não serao inicializados, nao que são vazios.
vazio = np.empty([3,2], dtype = int)
print(vazio)
print('---------')
zeros = np.zeros([4,3])
print(zeros)
print('---------')
um = np.ones([5,7])
print(um)
print('---------')
#cria matriz quadrada com diagonal principal com valores 1 e os outros valores zero
diagonal = np.eye(5)
print(diagonal)

[[1169923296        407]
 [         0          0]
 [         1  660930562]]
---------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
---------
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
---------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [9]:
#valores aleatorios entre zero e uum
ale = np.random.random((5))
print(ale)
print('-----------')
#valores aleatórios distr. normal contendo negativos
ale2 = np.random.randn((5))
print(ale2)
print('-----------')
ale3 = (10*np.random.random((3,4)))
print(ale3)

[0.25027182 0.71878038 0.2931212  0.727656   0.9407818 ]
-----------
[-1.47086113 -0.54869683  0.45409555  1.41163886 -0.44615596]
-----------
[[7.03360504 8.13746982 1.40955485 0.6644082 ]
 [6.88576467 1.75488324 1.1178052  0.66072092]
 [9.9097015  4.88447574 7.09282535 4.70708586]]


In [10]:
#outra forma de gerar aleatórios
#uso de semente

gnr = np.random.default_rng(1)
ale5 = gnr.random(3)
print(ale5)
print('-----------')
#gerar inteiros
ale6=gnr.integers(10, size= (3,4))
print(ale6)


[0.51182162 0.9504637  0.14415961]
-----------
[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [12]:
#unique remove repetições
j = np.array([11,11,11,12,13,14])
print(j)
print('-----------')
b = np.unique(j)
print(b)

[11 11 11 12 13 14]
-----------
[11 12 13 14]


[11 11 11 12 13 14]
-----------
[11 12 13 14]
